#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci= [0,1] #starts Fibonacci #s
x= 0 #x is which number we are currently on when creating a list of Fibonacci #s.
over_4_mil= False
total= 0 #Sum of even Fibonacci numbers

#Creates a list of Fibonacci #s under 4 mil
while over_4_mil == False:
    next_fib= fibonacci[x] + fibonacci [x+1]
    if next_fib < 4000000:
        fibonacci.append(next_fib)
        x+= 1
    else:
        over_4_mil = True

# Adds even Fibonacci #s
for i in fibonacci:
    if i % 2 == 0:
        total += i

print total
